name: Convert Markdown file index.md to index.html

on: [push]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo content               # fetch the contents of the repository
        uses: actions/checkout@v2
      - name: Prepare build environment
        run: |                                    # multiple Bash commands follow
          mkdir -p build
          touch build/.nojekyll
      - uses: docker://pandoc/core:2.12
        with:
          args: "index.md -o test.txt"
#          args: "index.md --css css/style.css -s --mathjax -t html5 -o index.html" # gets appended to pandoc command
#      - name: Deploy on github pages              # Use a third-party plugin to upload the content
#        uses: JamesIves/github-pages-deploy-action@4.1.0
#        with:
#          branch: main
#          folder: build 

#https://epcced.github.io/2022-06-20_docker_edi-wg/e01-github-actions/index.html`
