name: Convert Markdown file index.md to index.html

on: [push]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://pandoc/core:2.9
        with:
          args: "/../index.md --css css/style.css -s --mathjax -t html5 -o index.html" # gets appended to pandoc command
